
project_id = "vcxwikgasrttbngdygig"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.verify-paypal-payment]
verify_jwt = false

[functions.create-paypal-payment]
verify_jwt = false
