// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcauceokqbrmijjcqigo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jYXVjZW9rcWJybWlqamNxaWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTQyMzMsImV4cCI6MjA2Mjg3MDIzM30.qWQFZXugCgvisoo7wMFm_FHAvfJsjJPbdozPIbM9AHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);